---
grails:
    cors:
      enabled: true
    resources:
        pattern: '/**'
    profile: web
    codegen:
        defaultPackage: omar.ui
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: true
  health:
    enabled: true
  actuator:
    sensitive: false
  beans:
    sensitive: false
  metrics:
    sensitive: false
  configprops:
    sensitive: false
  trace:
    sensitive: false
  mappings:
    sensitive: false
  env:
    sensitive: false
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
# Client params
omar:
  openlayers:
    baseMaps:
      -
        layerType: "tilewms"
        title: "OSM Basic"
        url: "https://omar-dev.ossim.io/omar-mapproxy/service"
        params:
          layers: "o2-basemap-basic"
          format: "image/jpeg"
        options:
          visible: true
    # Uncomment the example below, and modify to add
    # a custom overlay layer
    overlayLayers:
      # -
      #   layerType: "tilewms"
      #   title: "DGI"
      #   url: "${serverProtocol}://${serverName}/geoscript-app/evwhs/wms"
      #   params:
      #     filter: ""
      #     version: "1.3.0"
      #     layers: ""
      #     styles: ""
      #     format: "image/png"
      #   options:
      #     visible: false
  app:
    userInfo:
      requestHeaderUserName: username
      requestHeaderUserNameDefault: Anonymous
    sites:
      -
        info:
          name: OMAR-LOCAL
          description: OMAR Local Server (Unclassified)
        url:
          base: http://localhost
    footprints:
      params: # misc params for the wfs request
        name: "Image Footprints"
        version: '1.1.1'
        layers: 'omar:raster_entry'
        styles: 'byFileType'
#        styles: 'bySensorType'
#        styles: 'byMissionType'
        format: 'image/gif'
    apiApp:
      baseUrl: http://localhost:8081/api
      enabled: true
    isaApp:
      enabled: true
    tlvApp:
      enabled: true
    twofishes:
      baseUrl: https://omar-dev.ossim.io/twofishes
      proxy: /twoFishesProxy
    kmlApp:
      enabled: true
    jpipApp:
      enabled: false
    piwikApp:
      enabled: false
    userGuide:
      baseUrl: http://localhost/o2-docs
      enabled: true
    misc:
      javascriptDebug: false
      splashModal:
        header: "O2 Notice"
        message: "Welcome to the O2 image discovery and analysis application."
        delay: 1000
        enabled: true
      beLookupEnabled: false
      # placemarks:
      #   tableName: omar:cities
      #   columnName: city_name
      #   geomName: geom
      #   maxResults: 100
      icons:
        greenMarker: assets/search_marker_green.png
      listRefreshButtonVisible: true
      totalPaginationCount: 1000
      pageLimit: 10
      motd:
        message: Be sure to check out the new federation capability by selecting an O2 server from the new dropdown box located above the result cards list!
        enabled: true
      about:
        enabled: true
        message: "O2 | Image Discovery and Analysis"
        releaseName: Egmont Key
        releaseNumber: 2.1.0
      metrics: # Metrics Dropdown Menu settings
        enabled: true
        admin:
          enabled: true # hide/show the Metrics Admin section
          hystrixTurbine: # The baseUrl below is a placeholder until we get Hystrix and Turbine working
            baseUrl: https://medium.com/netflix-techblog/hystrix-dashboard-turbine-stream-aggregator-60985a2e51df
            enabled: true
          sleuthZipkin: # The baseUrl below is a placeholder until we get Sleuth and Zipkin working
            baseUrl: https://spring.io/blog/2016/02/15/distributed-tracing-with-spring-cloud-sleuth-and-spring-cloud-zipkin
            enabled: true
          kibana:
            baseUrl: http://kibana.ossim.io
            enabled: true
        user:
          enabled: true # hide/show the Metrics Admin section
          eureka:
            baseUrl: http://eureka.omar-dev.ossim.io/omar-eureka-server
            enabled: true
---
classificationBanner:
  backgroundColor: green
  classificationType: Unclassified
  #backgroundColor: red
  #classificationType: Secret // NOFORN
    # backgroundColor: yellow
    # classificationType: Top Secret
